### PR TITLE
Restructure FAB and fix FAB while scroll

### LINKED ISSUE #145: Hide Floating action button on scroll
The FAB can hide the text behind it.
Make it so that it hides when scrolling down and comes back up when scrolling up.

Files concerned: 
* tripslist.dart
* dashboard.dart

### PR DESCRIPTION
**Pull request by rish07**
Fixes #145 and the problem faced in #162.

Working demo:
ezgif com-gif-maker

@kshitijalwadhi @Deepanshu-Rohilla  Let me know any changes if required.

### CODE REVIEW

**Comment by arpit-saxena** [comment]
Hey, you tagged the wrong person. You meant @Deepanshu-Rohilla

**Comment by rish07** [comment]
My bad @arpit-saxena

**Review by kshitijalwadhi — COMMENTED** [review]
Excellent work @rish07.
One thing that I was thinking was, would it be possible for you to add some animation to the FAB?
I have added a GIF which shows an example. 
Apart from this, the implementation looks great.

**Review by Deepanshu-Rohilla — APPROVED** [review]

**Comment by Deepanshu-Rohilla** [comment]
Working fine on my device. But yeah, animation would look great. 
https://flutter.dev/docs/development/ui/animations/hero-animations
@rish07 this might help.

**Comment by rish07** [comment]
Please check now @kshitijalwadhi @Deepanshu-Rohilla 
ezgif com-gif-maker

**Review by kshitijalwadhi — APPROVED** [review]
Excellent work @rish07. Looks great to me.
@tmibvishal sir I think this PR can be merged now. Pls review.

**Review by tmibvishal — APPROVED** [review]
Good Work

**Pull request merged**
