### PR TITLE
UI improvements

### LINKED ISSUE #98: "Leave Group" color changes
This bug was unnoticed in the meeting. 
On clicking the Leave Group button in the group page, the color of Group Button changes to black in light theme.
WhatsApp Video 2020-06-16 at 11 18 42 PM (2)

### PR DESCRIPTION
**Pull request by Deepanshu-Rohilla**
Fixes #98 
Following are the changes:
1. Shifted Logout from dashboard to user profile and in settings
WhatsApp Image 2020-06-16 at 11 18 41 PM (1)
WhatsApp Image 2020-06-16 at 11 18 41 PM (2)
WhatsApp Image 2020-06-16 at 11 18 41 PM

2. The card in group details had unnecessary top padding. So, adjusted the margin and padding of the card in group details
WhatsApp Image 2020-06-16 at 11 18 41 PM (4)
WhatsApp Image 2020-06-16 at 11 18 41 PM (5)

3. Following were icon changes (includes color change and icon removal)
WhatsApp Image 2020-06-16 at 11 18 41 PM (7)
WhatsApp Image 2020-06-16 at 11 18 41 PM (6)
WhatsApp Image 2020-06-16 at 11 18 41 PM (8)
WhatsApp Image 2020-06-16 at 11 18 41 PM (9)
WhatsApp Image 2020-06-16 at 11 18 41 PM (13)
WhatsApp Image 2020-06-16 at 11 18 41 PM (12)

4. Removed the bounce scrolling from notifications and triplist.
WhatsApp Video 2020-06-16 at 11 18 42 PM
WhatsApp Video 2020-06-16 at 11 18 41 PM
5. While leaving the group the color of "Leave Group" changed to black. That was to showcase that the button is disabled. But now the loading (while leaving the group) is replaced by the standard loading (as in sign out)
WhatsApp Video 2020-06-16 at 11 18 42 PM (2) (1)
WhatsApp Video 2020-06-17 at 1 57 28 PM

6. Removed the "Already in a Group Text" from top and from cards.
WhatsApp Image 2020-06-16 at 11 18 41 PM (11)
WhatsApp Image 2020-06-16 at 11 18 41 PM (10)

### CODE REVIEW

**Comment by Deepanshu-Rohilla** [comment]
Regarding issue #98 :
Present loading (while leaving the group) is replaced by the progress dialog used in signing out. Hence, issue #98 is solved.

**Comment by kshitijalwadhi** [comment]
The same settings panel is being showed in SignIn screen as well, so we cant show the logout button there. Add a condition to check if currentUser is there or not. 

```dart
var isLoggedIn=false;
final user = Provider.of<FirebaseUser>(context);
if(user!=null)
{
setState(() {
                  isLoggedIn=true;
                });
}
```

then use this variable to check if you need to show or not.

**Comment by kshitijalwadhi** [comment]
Also, instead of having onPressed on text, give an IconButton in trailing area, which onPressing would logout. This will make it consistent with the rest of UI.

**Comment by Deepanshu-Rohilla** [comment]
Implemented improvement suggested by @kshitijalwadhi . 
WhatsApp Video 2020-06-17 at 6 01 39 PM

**Pull request merged**
