### PR TITLE
Dialler feature

### LINKED ISSUE #73: Dialer on tapping phone icon

### LINKED ISSUE #77: The following RangeError was thrown building MyProfile...
**Assign to**
@kshitijalwadhi @Ishaan21

**To Reproduce**
Just launch the app. This is the first error that pops up

**Expected behavior**
```dart
I/flutter (28640): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28640): The following RangeError was thrown building MyProfile(dirty, dependencies:
I/flutter (28640): [InheritedProvider<FirebaseUser>], state: _MyProfileState#054a6):
I/flutter (28640): Value not in range: 1
I/flutter (28640): 
I/flutter (28640): The relevant error-causing widget was:
I/flutter (28640):   MyProfile
I/flutter (28640):   file:///Users/vishal/Desktop/Coding%20B/Flutter/workspace/shareacab/lib/screens/rootscreen.dart:39:18
I/flutter (28640): 
I/flutter (28640): When the exception was thrown, this was the stack:
I/flutter (28640): #0      _StringBase.substring (dart:core-patch/string_patch.dart:388:7)
I/flutter (28640): #1      _MyProfileState.build (package:shareacab/screens/profile/userprofile.dart:76:26)
I/flutter (28640): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter (28640): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (28640): #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (28640): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (28640): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (28640): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
I/flutter (28640): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (28640): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (28640): #10     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (28640): ...     Normal element mounting (7 frames)
I/flutter (28640): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (28640): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (28640): #19     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:116:18)
I/flutter (28640): #20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter (28640): #21     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:96:11)
I/flutter (28640): #22     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1866:58)
I/flutter (28640): #23     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
I/flutter (28640): #24     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1866:13)
I/flutter (28640): #25     RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:174:5)
I/flutter (28640): #26     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:244:5)
I/flutter (28640): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28640): #28     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
I/flutter (28640): #29     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
I/flutter (28640): #30     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
I/flutter (28640): #31     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
I/flutter (28640): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28640): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28640): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28640): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28640): #36     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1248:11)
I/flutter (28640): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28640): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28640): #39     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
I/flutter (28640): #40     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
I/flutter (28640): #41     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
I/flutter (28640): #42     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
I/flutter (28640): #43     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (28640): #44     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (28640): #45     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (28640): #46     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (28640): #50     _invoke (dart:ui/hooks.dart:261:10)
I/flutter (28640): #51     _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (28640): (elided 3 frames from dart:async)

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following RangeError was thrown building MyProfile(dirty, dependencies: [InheritedProvider<FirebaseUser>], state: _MyProfileState#9992c):
Value not in range: 1

The relevant error-causing widget was: 
  MyProfile file:///Users/vishal/Desktop/Coding%20B/Flutter/workspace/shareacab/lib/screens/rootscreen.dart:39:18
When the exception was thrown, this was the stack: 
#0      _StringBase.substring (dart:core-patch/string_patch.dart:388:7)
#1      _MyProfileState.build (package:shareacab/screens/profile/userprofile.dart:76:26)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Desktop (please complete the following information):**
 - OS: [e.g. Android]
 - Version [e.g. Android 8.1.0 Api level 27 ]

### LINKED ISSUE #78: Chat list not updating

### PR DESCRIPTION
**Pull request by Ishaan21**
In group details page and user profile, on tapping mobile num/icon, dialler pad opens up corresponding to that person.
Fixes #73, Fixes #77 , Fixes #78

### CODE REVIEW

**Comment by Ishaan21** [comment]
fixes #73

**Comment by tmibvishal** [comment]
```dart
E/MethodChannel#plugins.flutter.io/url_launcher(28640): Failed to handle method call
E/MethodChannel#plugins.flutter.io/url_launcher(28640): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=tel//9717482010 (has extras) }
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.app.Activity.startActivityForResult(Activity.java:4487)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.app.Activity.startActivityForResult(Activity.java:4445)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.app.Activity.startActivity(Activity.java:4806)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.app.Activity.startActivity(Activity.java:4774)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at io.flutter.plugins.urllauncher.UrlLauncher.launch(UrlLauncher.java:75)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onLaunch(MethodCallHandlerImpl.java:91)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:36)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#plugins.flutter.io/url_launcher(28640): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (28640): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=android.intent.action.VIEW dat=tel//9717482010 (has extras) }, null)
E/flutter (28640): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (28640): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (28640): <asynchronous suspension>
E/flutter (28640): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (28640): #3      MethodChannelUrlLauncher.launch (package:url_launcher_platform_interface/method_channel_url_launcher.dart:39:21)
E/flutter (28640): #4      launch (package:url_launcher/url_launcher.dart:88:58)
E/flutter (28640): #5      GroupDetails.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shareacab/screens/groupdetailscreen/groupdetails.dart:175:59)
E/flutter (28640): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (28640): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (28640): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (28640): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (28640): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (28640): #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter (28640): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (28640): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (28640): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (28640): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (28640): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (28640): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (28640): #18     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (28640): #19     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (28640): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (28640): #21     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (28640): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (28640): 
```
I am getting this error on clicking on call button in group 3
on Android 8.1.0 (api level 27) emulator

**Comment by Ishaan21** [comment]
There was a syntax error, resolved it.

**Comment by tmibvishal** [comment]
Call button not working in ios
try to find out if it is possible to call like that in ios and other thing you can do is. If device is ios just copy the number to clipboard and show a msg in snackbar number copied too clipboard

**Comment by Ishaan21** [comment]
Copy to Clipboard feature added, also on rapidly tapping there won't be a delay in SnackBar as previous one will hide.

**Pull request merged**
